# Generated by Django 6.0.7 on 2026-08-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="节点名称")),
                ("hostname", models.CharField(blank=True, max_length=255, verbose_name="主机名")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 地址")),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "在线"), ("offline", "离线")],
                        default="offline",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("cpu_percent", models.FloatField(default=0.0, verbose_name="CPU 使用率(%)")),
                ("mem_percent", models.FloatField(default=0.0, verbose_name="内存使用率(%)")),
                (
                    "last_heartbeat",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后心跳"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="注册时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "工作节点",
                "verbose_name_plural": "工作节点",
                "db_table": "nodes",
                "ordering": ["-last_heartbeat"],
            },
        ),
    ]
