# Generated by Django 6.0.7 on 2026-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="last_heartbeat",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="最后心跳"
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="status",
            field=models.CharField(
                choices=[("online", "在线"), ("offline", "离线")],
                db_index=True,
                default="offline",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
