# Generated by Django 6.0.7 on 2026-07-31 09:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "task_type",
                    models.CharField(
                        default="python_script", max_length=50, verbose_name="任务类型"
                    ),
                ),
                ("code", models.TextField(blank=True, verbose_name="执行代码/命令")),
                ("params", models.JSONField(blank=True, default=dict, verbose_name="任务参数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "普通"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(blank=True, max_length=100, verbose_name="执行节点"),
                ),
                ("result", models.JSONField(blank=True, default=dict, verbose_name="执行结果")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "db_table": "tasks",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
