# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cancel_requested_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="取消请求时间"),
        ),
    ]
