# Generated by Django 6.0.7 on 2026-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_cancel_requested_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("running", "执行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("timeout", "超时"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="worker_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="执行节点"
            ),
        ),
    ]
